apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: client
        image: 149083378091.dkr.ecr.us-east-1.amazonaws.com/multi-client:eks-workshop-sample-api-service-go.master..2020-08-13.07.29.21.d3823977
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
